version: "3.7"
services:
  app:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ../    
    restart: always
    volumes:
      - "../:/var/www/html/"
    ports:
      - "8080:80"
  mysql:
    image: mysql:latest
    # m1 mac対応
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      # https://docs.docker.jp/docker-for-mac/osxfs-caching.html
      # https://hfuji.hatenablog.jp/entry/2019/06/01/102617 cachedでマウントすると高速化できる
      - ".mysql-data:/var/lib/mysql:cached"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
volumes:
  mysql-data:
